using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Options;
using Shared.Audit.Configuration;
using Shared.Audit.Interfaces;
using Shared.Audit.Models;
namespace Shared.Audit.Interceptors
{
    public sealed class AuditSaveChangesInterceptor(
     IAuditMetadataProvider metadataProvider,
     IOptions<AuditOptions> options) : SaveChangesInterceptor
    {
        private readonly AuditOptions _config = options.Value;

        // State to hold entries between SavingChanges (Pre-Save) and SavedChanges (Post-Save)
        private List<AuditEntry>? _tempAuditEntries;

        // 1. BEFORE SAVE: Capture the intent (Modified/Deleted)
        public override async ValueTask<InterceptionResult<int>> SavingChangesAsync(
            DbContextEventData eventData,
            InterceptionResult<int> result,
            CancellationToken cancellationToken = default)
        {
            if (!_config.Enabled || eventData.Context is null)
                return await base.SavingChangesAsync(eventData, result, cancellationToken);

            // Store entries in the private field
            _tempAuditEntries = await CreateAuditEntries(eventData.Context);

            return await base.SavingChangesAsync(eventData, result, cancellationToken);
        }

        // 2. AFTER SAVE: Capture generated IDs and Write to DB
        public override async ValueTask<int> SavedChangesAsync(
            SaveChangesCompletedEventData eventData,
            int result,
            CancellationToken cancellationToken = default)
        {
            var context = eventData.Context;

            // Check if we have pending audit entries
            if (context is null || _tempAuditEntries is null || _tempAuditEntries.Count == 0)
                return await base.SavedChangesAsync(eventData, result, cancellationToken);

            try
            {
                // Update PKs for newly Added entities (now that they are generated by DB)
                foreach (var entry in _tempAuditEntries)
                {
                    foreach (var prop in entry.TemporaryProperties)
                    {
                        if (prop.Metadata.IsPrimaryKey())
                        {
                            entry.PrimaryKey = prop.CurrentValue?.ToString() ?? "Unknown";
                        }
                    }
                }

                // Write to DB using Raw SQL
                await WriteAuditLogsDirectlyAsync(context, _tempAuditEntries, cancellationToken);
            }
            finally
            {
                // Reset for the next SaveChanges call in the same request
                _tempAuditEntries = null;
            }

            return await base.SavedChangesAsync(eventData, result, cancellationToken);
        }

        private async Task<List<AuditEntry>> CreateAuditEntries(DbContext context)
        {
            context.ChangeTracker.DetectChanges();
            var userId = await metadataProvider.GetUserIdAsync();
            var list = new List<AuditEntry>();

            foreach (var entry in context.ChangeTracker.Entries())
            {
                if (entry.State == EntityState.Detached || entry.State == EntityState.Unchanged) continue;

                // Check Exclusions
                // GetTableName() requires Microsoft.EntityFrameworkCore.Relational
                var tableName = entry.Metadata.GetTableName() ?? entry.Entity.GetType().Name;

                if (_config.ExcludedTables.Contains(tableName)) continue;
                if (tableName == "AuditLogs") continue;

                var audit = new AuditEntry
                {
                    TableName = tableName,
                    UserId = userId,
                    Timestamp = DateTime.UtcNow,
                    Action = entry.State.ToString(),
                    PrimaryKey = "Unknown"
                };

                foreach (var prop in entry.Properties)
                {
                    if (prop.IsTemporary)
                    {
                        audit.TemporaryProperties.Add(prop);
                        continue;
                    }

                    string propName = prop.Metadata.Name;
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        audit.PrimaryKey = prop.CurrentValue?.ToString() ?? "Unknown";
                        continue;
                    }

                    switch (entry.State)
                    {
                        case EntityState.Added:
                            audit.NewValues[propName] = prop.CurrentValue;
                            audit.AffectedColumns.Add(propName);
                            break;
                        case EntityState.Deleted:
                            audit.OldValues[propName] = prop.OriginalValue;
                            audit.AffectedColumns.Add(propName);
                            break;
                        case EntityState.Modified:
                            if (prop.IsModified)
                            {
                                audit.OldValues[propName] = prop.OriginalValue;
                                audit.NewValues[propName] = prop.CurrentValue;
                                audit.AffectedColumns.Add(propName);
                            }
                            break;
                    }
                }
                list.Add(audit);
            }
            return list;
        }

        private static async Task WriteAuditLogsDirectlyAsync(
            DbContext context,
            List<AuditEntry> entries,
            CancellationToken ct)
        {
            // SQL Convention: We assume the table "AuditLogs" exists with these exact columns.
            const string sql = @"
            INSERT INTO AuditLogs 
            (UserId, Action, TableName, Timestamp, PrimaryKey, OldValues, NewValues, AffectedColumns) 
            VALUES 
            ({0}, {1}, {2}, {3}, {4}, {5}, {6}, {7})";

            foreach (var entry in entries)
            {
                await context.Database.ExecuteSqlRawAsync(sql,
                    [
                        entry.UserId,
                        entry.Action,
                        entry.TableName,
                        entry.Timestamp,
                        entry.PrimaryKey ?? "Unknown",
                        entry.SerializeOldValues(),
                        entry.SerializeNewValues(),
                        entry.SerializeAffected()
                    ], ct);
            }
        }
    }
}
